inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/{rails,rake}'
    - 'spec/dummy/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'
    - 'lib/zizia/spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/hyrax/basic_metadata.rb'
    - 'lib/zizia/hyrax/hyrax_record_importer.rb'
    - lib/zizia/importer.rb
    - lib/zizia/hyrax/hyrax_metadata_only_updater.rb
    - 'app/importers/modular_importer.rb'
    - 'app/lib/zizia/metadata_details.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/zizia/spec/**/*'
    - 'zizia.gemspec'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/zizia/hyrax/hyrax_basic_metadata_mapper.rb
    - lib/zizia/hyrax/hyrax_record_importer.rb

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/support/hyrax/basic_metadata.rb'
    - 'lib/zizia/hyrax/hyrax_basic_metadata_mapper.rb'
    - lib/zizia/hyrax/hyrax_record_importer.rb
    - 'app/importers/modular_importer.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - lib/zizia/hyrax_record_importer.rb

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/*_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/zizia/hyrax/hyrax_basic_metadata_mapper_spec.rb'
    - 'spec/integration/import_hyrax_csv.rb'
    - 'spec/integration/csv_import_detail_spec.rb'

RSpec/MessageSpies:
  Exclude:
    - spec/integration/import_csv_spec.rb

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/zizia/hyrax/hyrax_basic_metadata_mapper_spec.rb'
    - 'spec/integration/import_hyrax_csv.rb'
    - 'spec/controllers/importer_documentation_controller_spec.rb'
    - 'spec/integration/csv_import_detail_spec.rb'
    - 'spec/controllers/**/*'
Style/StructInheritance:
  Enabled: false
