version: 2.1
orbs:
    samvera: samvera/circleci-orb@0.3.1
jobs:
    build:
        parameters:
            ruby_version:
                type: string
                default: 2.5.3
            bundler_version:
                type: string
                default: 2.0.1
            rails_version:
                type: string
                default: 5.1.7
        executor:
            name: samvera/ruby_fcrepo_solr_redis
            ruby_version: << parameters.ruby_version >>
        working_directory: ~/project
        parallelism: 1
        environment:
          COVERALLS_PARALLEL: true
          RAILS_VERSION: << parameters.rails_version >>
        steps:
            - checkout

            - run:
                name: install sqlite3
                command: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

            - samvera/bundle:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>

            - samvera/rubocop

            - samvera/install_solr_core

            - run:
                name: install sqlite3
                command: bundle exec rake db:migrate

            - samvera/parallel_rspec
workflows:
    version: 2
    ci:
        jobs:
            - build:
                name: ruby2-5-8_with_rails_5_2
                ruby_version: "2.5.8"
                rails_version: "5.2.4.3"
            - build:
                name: ruby2-5-3_with_rails_5_2
                rails_version: 5.2.3
