version: 2.1
orbs:
    samvera: samvera/circleci-orb@0.3.2
jobs:
    build:
        parameters:
            ruby_version:
                type: string
                default: 2.5.3
            bundler_version:
                type: string
                default: 2.1.4
            rails_version:
                type: string
                default: 5.1.7
        executor:
            name: samvera/ruby_fcrepo_solr_redis
            ruby_version: << parameters.ruby_version >>
        working_directory: ~/project
        parallelism: 1
        environment:
          COVERALLS_PARALLEL: true
          COVERAGE: true
          RAILS_VERSION: << parameters.rails_version >>
          SOLR_URL: http://127.0.0.1:8985/solr/hydra-test
        steps:
            - checkout

            - run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev || true

            - samvera/bundle:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>

            - samvera/rubocop

            - samvera/install_solr_core

            - run:
                name: install sqlite3
                command: bundle exec rake db:migrate

            - samvera/parallel_rspec
workflows:
    version: 2
    ci:
        jobs:
            - build:
                name: ruby2-6-6_with_rails_5_2
                ruby_version: 2.6.6
                rails_version: 5.2.6
            - build:
                name: ruby2-7-4_with_rails_5_2
                ruby_version: 2.7.4
                rails_version: 5.2.6
