version: 2.1
orbs:
    samvera: samvera/circleci-orb@1.0.0
jobs:
    build:
        parameters:
            ruby_version:
                type: string
                default: 2.5.3
            bundler_version:
                type: string
                default: 2.1.4
            rails_version:
                type: string
                default: 5.1.7
        executor:
            name: samvera/ruby_fcrepo_solr_redis_postgres
            ruby_version: << parameters.ruby_version >>
        working_directory: ~/project
        parallelism: 1
        environment:
          DATABASE_URL: postgresql://postgres@127.0.0.1/circle_test
          DATABASE_NAME: circle_test
          POSTGRES_DB: circle_test
          DATABASE_USERNAME: postgres
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: postgres
          COVERALLS_PARALLEL: true
          RAILS_VERSION: << parameters.rails_version >>
        steps:
            - checkout

            - samvera/bundle:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>

            - samvera/rubocop

            - samvera/install_solr_core

            - samvera/parallel_rspec
workflows:
    version: 2
    ci:
        jobs:
            - build:
                name: ruby2-5-8_with_rails_5_2
                ruby_version: 2.5.8
                rails_version: 5.2.4.3
            - build:
                name: ruby2-6-6_with_rails_5_2
                ruby_version: 2.6.6
                rails_version: 5.2.4.3
            - build:
                name: ruby2-7-1_with_rails_5_2
                ruby_version: 2.7.1
                rails_version: 5.2.4.3
